import localFont from "next/font/local";
import "../public/globals.css";
import AsideMenu from "@/components/AsideMenu";

const geistMontserrat = localFont({
  src: "../public/fonts/Montserrat-Regular.ttf",
  variable: "--font-montserrat",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`${geistMontserrat.variable} antialiased flex`}
      >
        <AsideMenu />
        {children}
      </body>
    </html>
  );
}
